service: sharyn-serverless

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin

custom:
  webpack:
    config: webpack.functions.config.js
    includeModules:
      forceInclude:
        - knex
        - pg
  prune:
    automatic: true
    number: 3

functions:
  graphql:
    handler: src/functions/graphql.main
    events:
      - http:
          path: graphql
          method: any
          cors: true

  express:
    handler: src/functions/express.main
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{any+}
          method: any
