org: verekia
app: sharyn-serverless
service: sharyn-serverless

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    config: webpack.functions.config.js
    includeModules:
      forceInclude:
        - knex
        - pg

functions:
  graphql:
    handler: src/functions/graphql.main
    events:
      - http:
          path: graphql
          method: any
          cors: true

  get-notes:
    handler: src/functions/ssr.getNotes
    events:
      - http:
          path: ''
          method: get
          cors: true

  get-note:
    handler: src/functions/ssr.getNote
    events:
      - http:
          path: note/{id}
          method: get
          cors: true
