org: verekia
app: sharyn-boilerplate-serverless
service: sharyn-boilerplate-serverless

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    config: webpack.functions.config.js

functions:
  graphql:
    handler: src/functions/graphql.main
    events:
      - http:
          path: graphql
          method: any
          cors: true

  hello:
    handler: src/functions/hello.main
    events:
      - http:
          path: hello
          method: get
          cors: true
